repos:
  # --- Python backend hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
      - id: debug-statements
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
        files: ^backend/

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3.12
        files: ^backend/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3.12
        files: ^backend/

  # --- Frontend hooks ---
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@4.15.0
