# .pre-commit-config.yaml
default_install_hook_types: [pre-commit]
default_language_version:
  python: python3.12

repos:
  # --- Python backend hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: debug-statements # optional, but useful for catching leftover print/pdb

  # Black: auto-format Python code
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^backend/

  # # isort: auto-sort imports
  # - repo: https://github.com/PyCQA/isort
  #   rev: 6.0.1
  #   hooks:
  #     - id: isort
  #       language_version: python3.12
  #       files: ^backend/

  # Ruff: lint + auto-fix many Python issues
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^backend/

  # --- Frontend hooks (React / Vite) ---
  # Prettier: auto-format JS/TS/CSS/HTML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"

  # ESLint: lint + auto-fix JS/TS
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.34.0"
    hooks:
      - id: eslint
        additional_dependencies: ["eslint@9.6.0"]
        args: ["--config", "frontend/.eslint.config.js", "--fix"]
        files: ^frontend/
