[tool.ruff.lint]
# Only the core linting categories that catch real issues
select = [
    # pycodestyle: whitespace, formatting, etc.
    "E",
    "W",

    # Pyflakes: undefined names, unused imports
    "F",

    # flake8-bugbear: likely bugs and design problems
    "B",

    # security issues (Bandit)
    "S",
]

ignore = [
    # Ignore less important warnings that are often noisy
    "S104",      # e.g., use of assert in production code
    "PLR6201",   # pylint-style warnings
    "S101"       # assert statements in code
]

[tool.ruff.format]
# Prefer double quotes over single quotes
quote-style = "double"
# Use spaces instead of tabs
indent-style = "space"
# Enable reformatting of code snippets in docstrings
docstring-code-format = true
skip-magic-trailing-comma = true
