from datetime import date, datetime, time

# --- USERS (12 total) ---
users = [
    {
        "id": 1,
        "name": "Alice",
        "surname": "Smith",
        "email": "alice@example.com",
        "password": "alice123",
        "active": True,
        "phone_number": "1234567890",
        "role": "player",
        "address": "Athens, Greece",
        "date_of_birth": date(1990, 1, 15),
        "profession": "Engineer",
        "created_at": datetime(2025, 8, 31, 8, 0),
    },
    {
        "id": 2,
        "name": "Bob",
        "surname": "Johnson",
        "email": "bob@example.com",
        "password": "bob456",
        "active": True,
        "phone_number": "2345678901",
        "role": "player",
        "address": "Crete, Greece",
        "date_of_birth": date(1988, 5, 20),
        "profession": "Teacher",
        "created_at": datetime(2025, 8, 31, 8, 5),
    },
    {
        "id": 3,
        "name": "Carol",
        "surname": "White",
        "email": "carol@example.com",
        "password": "carol789",
        "active": True,
        "phone_number": "3456789012",
        "role": "admin",
        "address": "Thessaloniki, Greece",
        "date_of_birth": date(1985, 3, 10),
        "profession": "Manager",
        "created_at": datetime(2025, 8, 31, 8, 10),
    },
    {
        "id": 4,
        "name": "David",
        "surname": "Lee",
        "email": "david@example.com",
        "password": "david123",
        "active": True,
        "phone_number": "4567890123",
        "role": "player",
        "address": "Patras, Greece",
        "date_of_birth": date(1992, 7, 12),
        "profession": "Doctor",
        "created_at": datetime(2025, 8, 31, 8, 15),
    },
    {
        "id": 5,
        "name": "Emma",
        "surname": "Davis",
        "email": "emma@example.com",
        "password": "emma456",
        "active": True,
        "phone_number": "5678901234",
        "role": "player",
        "address": "Rhodes, Greece",
        "date_of_birth": date(1991, 9, 30),
        "profession": "Artist",
        "created_at": datetime(2025, 8, 31, 8, 20),
    },
    {
        "id": 6,
        "name": "Frank",
        "surname": "Miller",
        "email": "frank@example.com",
        "password": "frank123",
        "active": True,
        "phone_number": "6789012345",
        "role": "player",
        "address": "Larissa, Greece",
        "date_of_birth": date(1987, 11, 5),
        "profession": "Engineer",
        "created_at": datetime(2025, 8, 31, 8, 25),
    },
    {
        "id": 7,
        "name": "Grace",
        "surname": "Lee",
        "email": "grace@example.com",
        "password": "grace456",
        "active": True,
        "phone_number": "7890123456",
        "role": "player",
        "address": "Kavala, Greece",
        "date_of_birth": date(1993, 4, 18),
        "profession": "Lawyer",
        "created_at": datetime(2025, 8, 31, 8, 30),
    },
    {
        "id": 8,
        "name": "Henry",
        "surname": "Adams",
        "email": "henry@example.com",
        "password": "henry123",
        "active": True,
        "phone_number": "8901234567",
        "role": "player",
        "address": "Ioannina, Greece",
        "date_of_birth": date(1989, 6, 22),
        "profession": "Teacher",
        "created_at": datetime(2025, 8, 31, 8, 35),
    },
    {
        "id": 9,
        "name": "Isabel",
        "surname": "Clark",
        "email": "isabel@example.com",
        "password": "isabel456",
        "active": True,
        "phone_number": "9012345678",
        "role": "player",
        "address": "Chania, Greece",
        "date_of_birth": date(1994, 2, 14),
        "profession": "Engineer",
        "created_at": datetime(2025, 8, 31, 8, 40),
    },
    {
        "id": 10,
        "name": "Jack",
        "surname": "Turner",
        "email": "jack@example.com",
        "password": "jack123",
        "active": True,
        "phone_number": "0123456789",
        "role": "player",
        "address": "Volos, Greece",
        "date_of_birth": date(1990, 12, 3),
        "profession": "Designer",
        "created_at": datetime(2025, 8, 31, 8, 45),
    },
    {
        "id": 11,
        "name": "Karen",
        "surname": "Hall",
        "email": "karen@example.com",
        "password": "karen456",
        "active": True,
        "phone_number": "1123456789",
        "role": "player",
        "address": "Heraklion, Greece",
        "date_of_birth": date(1986, 10, 8),
        "profession": "Nurse",
        "created_at": datetime(2025, 8, 31, 8, 50),
    },
    {
        "id": 12,
        "name": "Leo",
        "surname": "Scott",
        "email": "leo@example.com",
        "password": "leo123",
        "active": True,
        "phone_number": "2123456789",
        "role": "player",
        "address": "Mykonos, Greece",
        "date_of_birth": date(1995, 8, 9),
        "profession": "Student",
        "created_at": datetime(2025, 8, 31, 8, 55),
    },
    {
        "id": 13,
        "name": "Ioannis",
        "surname": "Maragkakis",
        "email": "giannis.marar@hotmail.com",
        "password": "ioannis123",
        "active": True,
        "phone_number": "6982972144",
        "role": "admin",
        "address": "Chania, Greece",
        "date_of_birth": date(1995, 4, 9),
        "profession": "Data Scientist",
        "created_at": datetime(2025, 8, 31, 8, 55),
    },
]


# --- COURTS (5 total) ---
courts = [
    {
        "id": 1,
        "name": "Court 1",
        "status": "available",
        "professional": False,
        "description": "Main court",
    },
    {
        "id": 2,
        "name": "Court 2",
        "status": "available",
        "professional": False,
        "description": "Side court",
    },
    {
        "id": 3,
        "name": "Court 3",
        "status": "maintenance",
        "professional": False,
        "description": "Under repair",
    },
    {
        "id": 4,
        "name": "Court 4",
        "status": "available",
        "professional": False,
        "description": "Outdoor court",
    },
    {
        "id": 5,
        "name": "Court 5",
        "status": "available",
        "professional": False,
        "description": "Indoor court",
    },
]

# --- TIMESLOTS (4 total) ---
timeslots = [
    {
        "id": 1,
        "start_time": time(15, 0),
        "end_time": time(16, 30),
        "status": "available",
        "description": None,
    },
    {
        "id": 2,
        "start_time": time(16, 30),
        "end_time": time(18, 0),
        "status": "available",
        "description": None,
    },
    {
        "id": 3,
        "start_time": time(18, 0),
        "end_time": time(19, 30),
        "status": "available",
        "description": None,
    },
    {
        "id": 4,
        "start_time": time(19, 30),
        "end_time": time(21, 0),
        "status": "available",
        "description": None,
    },
    {
        "id": 5,
        "start_time": time(21, 0),
        "end_time": time(22, 30),
        "status": "available",
        "description": None,
    },
]

# --- RESERVATIONS (3 reservations × 4 players each) ---
reservations = []

# --- RESERVATION USERS (linking each reservation to 4 players) ---
reservation_players = []
